<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Travaux Efficom</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Valentin Silvestre</h1>
        <div>Présentation des projets</div>

        <hr>

        <div class="container">
            <h3><u>Url de base :</u> http://api.vsilvestre.fr/</h3>
            <hr>
            <h3>GET</h3>
            <div class="table-responsive">
                <table class="table table-bordered text-center">
                    <tr>
                        <th>Objectif</th>
                        <th>URL</th>
                        <th>Arguments</th>
                    </tr>
                    <tr>
                        <th>Toutes les interventions</th>
                        <td>interventions/</td>
                        <td><i>null</i></td>
                    </tr>
                    <tr>
                        <th>Toutes les positions</th>
                        <td>positions/</td>
                        <td><i>null</i></td>
                    </tr>
                    <tr>
                        <th>Tout les techniciens</th>
                        <td>techniciens/</td>
                        <td><i>null</i></td>
                    </tr>
                    <tr>
                        <th>Une intervention</th>
                        <td>interventions/{id}</td>
                        <td><i>Id de l'intervention</i></td>
                    </tr>
                    <tr>
                        <th>Une position d'un matériel</th>
                        <td>positions/{imei}</td>
                        <td><i>IMEI</i></td>
                    </tr>
                    <tr>
                        <th>Un technicien</th>
                        <td>techniciens/{id}</td>
                        <td><i>Id du technicien</i></td>
                    </tr>
                </table>
            </div>
            <hr>
            <h3>POST</h3>
            <div class="table-responsive">
                <table class="table table-bordered text-center">
                    <tr>
                        <th>Objectif</th>
                        <th>URL</th>
                        <th>Arguments</th>
                    </tr>
                    <tr>
                        <th>Une intervention</th>
                        <td>interventions/{id}</td>
                        <td><i>Id de l'intervention</i></td>
                    </tr>
                    <tr>
                        <th>Une position d'un matériel</th>
                        <td>positions/{imei}</td>
                        <td><i>IMEI</i></td>
                    </tr>
                    <tr>
                        <th>Un technicien</th>
                        <td>techniciens/{id}</td>
                        <td><i>Id du technicien</i></td>
                    </tr>
                </table>
            </div>
            <hr>
            <h3>PUT</h3>
            <div class="table-responsive">
                <table class="table table-bordered text-center">
                    <tr>
                        <th>Objectif</th>
                        <th>URL</th>
                        <th>Arguments</th>
                    </tr>
                    <tr>
                        <th>Une intervention</th>
                        <td>interventions/{id}</td>
                        <td><i>Id de l'intervention</i></td>
                    </tr>
                    <tr>
                        <th>Une position d'un matériel</th>
                        <td>positions/{imei}</td>
                        <td><i>IMEI</i></td>
                    </tr>
                    <tr>
                        <th>Un technicien</th>
                        <td>techniciens/{id}</td>
                        <td><i>Id du technicien</i></td>
                    </tr>
                </table>
            </div>
            <hr>
            <h3>DELETE</h3>
            <div class="table-responsive">
                <table class="table table-bordered text-center">
                    <tr>
                        <th>Objectif</th>
                        <th>URL</th>
                        <th>Arguments</th>
                    </tr>
                    <tr>
                        <th>Une intervention</th>
                        <td>interventions/{id}</td>
                        <td><i>Id de l'intervention</i></td>
                    </tr>
                    <tr>
                        <th>Une position d'un matériel</th>
                        <td>positions/{imei}</td>
                        <td><i>IMEI</i></td>
                    </tr>
                    <tr>
                        <th>Un technicien</th>
                        <td>techniciens/{id}</td>
                        <td><i>Id du technicien</i></td>
                    </tr>
                </table>
            </div>
        </div>
    </body>
</html>
